name: Update Google Sheets every 5 minutes

on:
  schedule:
    - cron: '30 3 * * *'
    - cron: '35 3 * * *'
    - cron: '40 3 * * *'
    - cron: '45 3 * * *'
    - cron: '50 3 * * *'
    - cron: '55 3 * * *'
    - cron: '0 4 * * *'  
  workflow_dispatch:

jobs:
  update-sheet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set service account JSON
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: echo "$SERVICE_ACCOUNT_JSON" > service_account.json

      - name: Run main.py
        run: python main.py
